bizland/bizland/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.views.i18n import set_language




urlpatterns = [
    path('admin123321/', admin.site.urls),
    
    
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + i18n_patterns(
    path("", include('info.urls')),
    path('set_language/', set_language, name='set_language'),

)

bizland/info/urls.py
from django.urls import path
from . import views




app_name='info'

urlpatterns = [
    path("", views.index,name='index'),
    path("service-detail/<int:id>/", views.service_detail, name='service-detail'),
]

bizland/info/models.py
from django.db import models
from ckeditor.fields import RichTextField




class TeamMember(models.Model):
    name = models.CharField(max_length=100)
    position = models.CharField(max_length=100)
    image = models.ImageField()
    
    def __str__(self):
        return self.name



class Service(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    icon_class = models.CharField(max_length=50)  

    def __str__(self):
        return self.title
    
class ServiceDetail(models.Model):
    service = models.ForeignKey(Service, on_delete=models.CASCADE, related_name='details')
    image = models.ImageField(upload_to='service_images/', null=True, blank=True)  # Fotoğraf alanı
    title = models.CharField(max_length=200)
    description = RichTextField() 
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"Detail for {self.service.title}: {self.title}"
    

class PortfolioItem(models.Model):
    CATEGORY_CHOICES = [
        ('2g', '2G Avadanlıqlar'),  # Mevcut kategori
        ('4g', '4G Avadanlıqlar'),  # Mevcut kategori
        ('sensor', 'Sensorlar'),    # Mevcut kategori
        ('topography', 'Topoqrafiya Avadanlıqları'),  # Yeni kategori
    ]

    title = models.CharField(max_length=255)
    description = models.TextField()
    image = models.ImageField(upload_to='portfolio_images/')
    category = models.CharField(max_length=20, choices=CATEGORY_CHOICES)
    detail_url = models.URLField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title
    
    def __str__(self):
        return self.title


class FAQ(models.Model):
    question = models.CharField(max_length=255)  
    answer = models.TextField()                    
    is_active = models.BooleanField(default=True)  

    def __str__(self):
        return self.question
    


class ContactMessage(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    subject = models.CharField(max_length=200)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.subject


class Client(models.Model):
    name = models.CharField(max_length=100)
    logo = models.ImageField(upload_to='clients/logos/')
    url = models.URLField(max_length=200, blank=True, null=True)
    order = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['order', '-created_at']


class MenuItem(models.Model):
    title = models.CharField(max_length=255)
    link = models.URLField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title
    

bizland/info/forms.py
from django import forms
from .models import ContactMessage

class ContactForm(forms.ModelForm):
    class Meta:
        model = ContactMessage
        fields = ['name', 'email', 'subject', 'message']

bizland/info/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .models import TeamMember,Service,FAQ,ContactMessage,Client,PortfolioItem,MenuItem
from .forms import ContactForm
from django.contrib import messages






# Create your views here.
def index(request):
    team_members = TeamMember.objects.all()
    services = Service.objects.all()
    portfolio_items = PortfolioItem.objects.all()  # Tüm portföy öğelerini al
    faqs = FAQ.objects.filter(is_active=True)
    clients = Client.objects.all()
    menu_items = MenuItem.objects.all()


    
    form = ContactForm()

    if request.method == 'POST':
        form = ContactForm(request.POST)  
        if form.is_valid():
            form.save()  
            messages.success(request, 'Mesajınız uğurla gondərildi!')
            form = ContactForm()
        else:
            messages.error(request, 'Problem baş verdi,Xahiş olunur təkrar cəhd edin!')

    return render(request, 'index.html', {
        'form': form,
        'team_members': team_members,
        'services': services,
        'faqs': faqs,
        'clients': clients,
        'portfolio_items': portfolio_items,
        'menu_items': menu_items,
        
    })


def service_detail(request, id):
    service = get_object_or_404(Service, id=id)
    service_details = service.details.all()  # Ters ilişkiyi kullanarak ServiceDetail'ları alıyoruz
    return render(request, 'service-detail.html', {'service': service, 'service_details': service_details})

bizland/info/templates/service-detail.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <title>Service Details - BizLand Bootstrap Template</title>
  <meta name="description" content="">
  <meta name="keywords" content="">

  <!-- Favicons -->
  <link href="{% static 'assets/img/favicon.png' %}" rel="icon">
  <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Fonts -->
  <link href="https://fonts.googleapis.com" rel="preconnect">
  <link href="https://fonts.gstatic.com" rel="preconnect" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;1,300;1,400;1,500;1,600;1,700;1,800&family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css'%}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css'%}" rel="stylesheet">
  <link href="{% static 'assets/vendor/aos/aos.css'%}" rel="stylesheet">
  <link href="{% static 'assets/vendor/glightbox/css/glightbox.min.css'%}" rel="stylesheet">
  <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css'%}" rel="stylesheet">

  <!-- Main CSS File -->
  <link href="{% static 'assets/css/main.css' %}" rel="stylesheet">

  <!-- =======================================================
  * Template Name: BizLand
  * Template URL: https://bootstrapmade.com/bizland-bootstrap-business-template/
  * Updated: Aug 07 2024 with Bootstrap v5.3.3
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body class="service-details-page">

  <header id="header" class="header sticky-top">



    <div class="branding d-flex align-items-cente">

      <div class="container position-relative d-flex align-items-center justify-content-between">
        <a href="{% url 'info:index' %}" class="logo d-flex align-items-center">
          <img src="{% static 'assets/img/logo.png' %}" alt=""> 
        </a>

        <nav id="navmenu" class="navmenu">
          <ul>
            <li><a href="{% url 'info:index' %}">{% trans "Ana Səhifə" %}</a></li>
      
          </ul>
          <i class="mobile-nav-toggle d-xl-none bi bi-list"></i>
        </nav>

      </div>

    </div>

  </header>

  <main class="main">

    <!-- Page Title -->
    
    <!-- Service Details Section -->
    <section id="service-details" class="service-details section">
      <div class="container">
          <div class="row gy-4">
              
              {% for detail in service_details %}
              <div class="col-lg-4" data-aos="fade-up" data-aos-delay="100">
                  <div class="service-image">
                      <img src="{{ detail.image.url }}" alt="Service Image" class="img-fluid">
                  </div>
              </div>
  
              <div class="col-lg-8" data-aos="fade-up" data-aos-delay="200">
                  <h3>{{ detail.title }}</h3>
                  <p>{{ detail.description|safe }}</p>
              </div>
              {% endfor %}
  
          </div>
      </div>
  </section>

  </main>

 


  <!-- Scroll Top -->
  <a href="#" id="scroll-top" class="scroll-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Preloader -->
  <div id="preloader">
    <div></div>
    <div></div>
    <div></div>
    <div></div>
  </div>

  <!-- Vendor JS Files -->
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>
  <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>
  <script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'assets/vendor/waypoints/noframework.waypoints.js' %}"></script>
  <script src="{% static 'assets/vendor/purecounter/purecounter_vanilla.js' %}"></script>
  <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/imagesloaded/imagesloaded.pkgd.min.js' %}"></script>
  <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>

  <!-- Main JS File -->
  <script src="{% static 'assets/js/main.js' %}"></script>

</body>

</html>